SUBROUTINE DP86CO()
IMPLICIT DOUBLE PRECISION (A-H,O-Z)
COMMON /CONDO8/XOLD,HOUT
RETURN
END

DOUBLE PRECISION FUNCTION CONTD8()
IMPLICIT DOUBLE PRECISION (A-H,O-Z)
COMMON /CONDO8/XOLD,H
S = H
RETURN
END

PROGRAM COMMON_12
END PROGRAM